### ISSUE TITLE
missing two files in the dataset

### ISSUE THREAD

**Issue by wind-xin** [youngandbin/PfoTGNRec#1]
In the dataset, I couldn't find these two files: ml_transaction_user.npy, ml_transaction_item.npy. 
Could you please upload the relevant files? Or let me know where I can find these two files? I would be very grateful. Thank you very much.

**Comment by youngandbin** [comment]
Those two files are not used in this work. I am sorry for the confusion. I have updated codes so that the codes will not use those files anymore!

**Comment by wind-xin** [comment]
Thank you for your response. I have a follow-up question regarding the datasets. 
The dataset  is labeled 'period_all', yet the program code requires 'period_30'. Similar questions persist regarding the `time_feature_past.pkl` and `time_feature_future.pkl` files, which are mentioned in the code but are not found in the dataset.
Could you guide me on how to transform them? And the If possible, could you share the corresponding code? Thank you again for your sharing.

**Comment by wind-xin** [comment]
When I run the new code you uploaded, I still encounter an error. An error occurs on line 106 of main.py when creating the tgn class, and on line 85 of tgn.py.
Raise TypeError: get_embedding_module() missing 4 required positional arguments: 'user_features', 'item_features', 'user_encoder', and 'item_encoder'.

**Comment by youngandbin** [comment]
I have updated the data `period_30` in google drive, which indicates 30 days of evaluation. I am sorry for the confusion. Also, the `main.py` is updated.

**Comment by wind-xin** [comment]
Thank you very much for your insights and your patient responses in our interactions. After running the code with the default hyperparameters, I've noticed a considerable gap in the performance metrics compared to the results highlighted in the academic paper.  I'm left wondering if this issue might stem from the hyperparameter configuration. Should you be able to provide the optimal hyperparameters, I would be extremely grateful. Thank you again for your sharing.
